"""inital db

Revision ID: 608caf665f86
Revises: 
Create Date: 2021-07-18 21:37:37.015286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608caf665f86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conditions',
    sa.Column('sign', sa.Enum('LESS_THAN', 'LESS_EQUAL', 'GREATER_THAN', 'GREATER_EQUAL', name='conditionenum'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('sign')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('condition', sa.Integer(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['condition'], ['conditions.sign'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'subscriber_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('rules')
    op.drop_table('conditions')
    # ### end Alembic commands ###
